# Generated by Django 4.2.2 on 2023-07-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MenuItemsAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"verbose_name_plural": "MenuItems"},
        ),
        migrations.AddField(
            model_name="menuitem",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
