# Generated by Django 4.2.2 on 2023-07-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MenuItemsAPI", "0002_alter_menuitem_options_menuitem_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.IntegerField(default=1),
        ),
    ]
