# Generated by Django 4.2.2 on 2023-07-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MenuItemsAPI", "0005_alter_category_options_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
